#!/usr/bin/env bash
#display information about subdomains

func () {
    dig "$1"."$2" | awk '/ANSWER SECTION/ { getline; print $0 }' | awk 'split($1,a,".") {print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
}

if [ "$#" -eq 2 ]; then
    func "$2" "$1"
else
    list=("www" "lb-01" "web-01" "web-02")
    for sub in "${list[@]}"; do
        func "$sub" "$1"
    done
fi
