#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | tee /var/www/html/index.html
sudo service nginx restart
