#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Holberton School" > sudo tee /var/www/html/index.html
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-enabled/default"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restart
