#!/usr/bin/env bash
# response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install -y nginx
sed -i "30 i \\\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
