#!/usr/bin/env bash
#Configure HAproxy with version equal or greater than 1.5
#so that it send traffic to web-01 and web-02

echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
      tee /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install -y haproxy -t trusty-backports
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sed -i "6 i \\\nENABLED=1\n" /etc/default/haproxy
sed -i "\$a\
listen backend *:80\n\
\tmode http\n\tbalance roundrobin\n\
\tserver 1503-web-01 104.196.204.4:80 check\n\
\tserver 1503-web-02 35.231.4.186:80 check\n" \
/etc/haproxy/haproxy.cfg
sudo service haproxy start
